Update cook_k_xcl2212.yml

diff --git a/.github/workflows/cook_k_xcl2212.yml b/.github/workflows/cook_k_xcl2212.yml
--- a/.github/workflows/cook_k_xcl2212.yml
+++ b/.github/workflows/cook_k_xcl2212.yml
@@ -1038,7 +1038,7 @@ jobs:
         working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
         run: |
           set -e
-          rm -rf ./KernelSU ./drivers/kernelsu
+          rm -rf ./KernelSU-Next ./drivers/kernelsu
           
           curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s dev
           echo "✔ KSUN installed successfully"
@@ -1073,11 +1073,11 @@ jobs:
 
           echo "🔧 Applying Syscall hooks -> KernelSU patch..."
           curl -L -o hooks.patch "https://raw.githubusercontent.com/nebixts/kernel_patches/main/scope_min_manual_hooks_v1.9.patch"
-          patch -p1 < hooks.patch || echo "Warning: Syscall hooks failed"
+          patch -p1 -f < hooks.patch || echo "Warning: Syscall hooks failed"
           echo "✔ Applied syscall hooks successfully"
           
           if [ ! -d "drivers/kernelsu" ]; then
-            ln -sf ../KernelSU drivers/kernelsu
+            ln -sf ../KernelSU-Next drivers/kernelsu
             echo "✔ Created drivers/kernelsu symlink"
           fi
           
