Update and rename Cook_K_LCL22.yml to Cook_K_A_Build.yml

diff --git a/.github/workflows/Cook_K_A_Build.yml b/.github/workflows/Cook_K_A_Build.yml
--- a/.github/workflows/Cook_K_A_Build.yml
+++ b/.github/workflows/Cook_K_A_Build.yml
@@ -1,4 +1,4 @@
-name: "Cook_K_XCL22"
+name: "Cook_K_Advanced_Build"
 
 env:
   OUT_DIR: "out"
@@ -33,6 +33,15 @@ on:
         required: false
         type: string
         default: "-NeFaRiaN-3.5-G-22052026"
+      Toolchain:
+        description: "Choose Toolchain Compiler"
+        required: false
+        type: choice
+        default: "LLVM"
+        options:
+          - "ACLANG"
+          - "XCLANG"
+          - "LLVM"
       buildKSU:
         description: "Build KSU variant?"
         required: true
@@ -229,7 +238,125 @@ jobs:
       
       # ====================== Source Code Preparation Stage ======================
     
+      - name: "📥 Initialize ToolChain Repo"
+        if: github.event.inputs.Toolchain == 'ACLANG'
+        working-directory: ${{ env.WORK_DIR}}
+        run: |
+          repo init -u https://android.googlesource.com/kernel/manifest -b common-android13-5.15-lts --depth=1
+          repo sync --optimized-fetch --prune --no-clone-bundle --no-tags -j$(nproc --all)
+          
+          rm -rf .repo
+          rm -rf common
+                                                                                    
+          aria2c -x 16 -s 16 -o prebuilts/clang/host/linux-x86/clang-r596125.tar.gz "https://github.com/nebixts/clang_L/releases/download/v2.0.2/clang-r596125.tar.gz"
+          mkdir -p prebuilts/clang/host/linux-x86/clang-r596125
+          tar -xzf prebuilts/clang/host/linux-x86/clang-r596125.tar.gz -C prebuilts/clang/host/linux-x86/clang-r596125
+          rm -rf prebuilts/clang/host/linux-x86/clang-r596125.tar.gz
+
+          rm -rf prebuilts/clang/host/linux-x86/clang-r547379
+          rm -rf prebuilts/clang/host/linux-x86/clang-3289846
+          rm -rf prebuilts/clang/host/linux-x86/clang-r450784e
+          rm -rf prebuilts/clang/host/linux-x86/clang-stable
+         
+          sed -i \
+           -e 's/^BRANCH=.*/BRANCH=android13-5.15/' \
+           -e 's/^CLANG_VERSION=.*/CLANG_VERSION=r596125/' \
+           ${{ env.kernelDir }}/${{ env.kernelName }}/build.config.constants
+          
+          sed -i '/^DEFCONFIG=gki_defconfig/d' ${{ env.kernelDir }}/${{ env.kernelName }}/build.config.gki
+          sed -i '$a\DEFCONFIG=${{ env.DEFCONFIG_NAME }}' ${{ env.kernelDir }}/${{ env.kernelName }}/build.config.gki
+          sed -i '/^POST_DEFCONFIG_CMDS="check_defconfig"/d' ${{ env.kernelDir }}/${{ env.kernelName }}/build.config.gki
+
+          sed -i \
+           -e '/^KMI_SYMBOL_LIST_STRICT_MODE=/d' \
+           -e '/^TRIM_NONLISTED_KMI=/d' \
+           -e '/^KMI_ENFORCED=/d' \
+           -e '$a\KMI_SYMBOL_LIST_STRICT_MODE=0' \
+           -e '$a\TRIM_NONLISTED_KMI=0' \
+           -e '$a\KMI_ENFORCED=0' \
+           -e '/^MODULES_ORDER=/d' \
+           -e '/^MODULES_LIST=/d' \
+           ${{ env.kernelDir }}/${{ env.kernelName }}/build.config.gki.aarch64
+      
       - name: "⚙️ Initialize Toolchains Repo"
+        if: github.event.inputs.Toolchain == 'XCLANG'
+        run: |
+          set -e
+      
+          get_latest_github_release() {
+            local repo_url="$1"
+            latest_url=$(curl -sL "https://api.github.com/repos/$repo_url/releases/latest" | grep "browser_download_url.*tar.gz" | cut -d '"' -f 4 | head -n 1)
+            
+            if [[ -z "$latest_url" ]]; then
+              echo "❌ Failed to fetch latest release from $repo_url!"
+              exit 1
+            fi
+      
+            printf "%s" "$latest_url"
+          }
+      
+          clang_url=$(get_latest_github_release "Xtra-Manager-Software/XClang-Binaries")
+      
+          echo "✅ Clang URL: $clang_url"
+      
+          mkdir -p clang
+      
+          if [[ "$clang_url" == *.tar.gz ]]; then
+            echo "🚀 Downloading latest Clang from: $clang_url..."
+            wget --progress=bar:force -O "clang/clang.tar.gz" "$clang_url" || { echo "❌ Failed to download Clang!"; exit 1; }
+      
+            echo "📦 Extracting Clang..."
+            tar -xf clang/clang.tar.gz -C clang || { echo "❌ Extraction failed!"; exit 1; }
+            rm -f clang/clang.tar.gz
+          else
+            echo "🚀 Cloning Clang from $clang_url..."
+            git clone --recursive --depth=1 "$clang_url" clang || { echo "❌ Cloning failed!"; exit 1; }
+          fi
+      
+          if [ -d "clang/bin" ]; then
+            CLANG_PATH="${{ github.workspace }}/clang/bin"
+          else
+            CLANG_PATH=$(find clang -type d -name "bin" | head -n 1)
+            CLANG_PATH="${{ github.workspace }}/${CLANG_PATH}"
+          fi
+      
+          if [ ! -f "$CLANG_PATH/clang" ]; then
+            echo "❌ Clang binary not found in $CLANG_PATH! Build might fail."
+            ls -R clang
+            exit 1
+          fi
+      
+          echo "✅ Using Clang from $CLANG_PATH"
+          echo "CLANG_PATH=$CLANG_PATH" >> $GITHUB_ENV
+          echo "$CLANG_PATH" >> $GITHUB_PATH
+      
+          export PATH="$CLANG_PATH:$PATH"
+          export CLANG_TRIPLE="aarch64-linux-gnu-"
+          export CC=clang
+          export AR="llvm-ar"
+          export AS="llvm-as"
+          export NM="llvm-nm"
+          export OBJCOPY="llvm-objcopy"
+          export OBJDUMP="llvm-objdump"
+          export STRIP="llvm-strip"
+          
+          echo "⚙️ Using Clang version:"
+          clang --version || echo "❌ Clang not found in PATH!"
+
+          TC_ROOT="${CLANG_PATH%/bin}"
+          TC_LIB_DIR="$TC_ROOT/lib"
+          
+          echo "🔧 Fixing libxml2 in $TC_LIB_DIR..."
+          mkdir -p "$TC_LIB_DIR"
+          
+          ln -sf /usr/lib/x86_64-linux-gnu/libxml2.so.2 "$TC_LIB_DIR/libxml2.so.16"
+          
+          echo "LD_LIBRARY_PATH=$TC_LIB_DIR:$LD_LIBRARY_PATH" >> $GITHUB_ENV
+          
+          echo "✅ Toolchain setup complete."
+      
+      - name: "⚙️ Initialize Toolchains Repo"
+        if: github.event.inputs.Toolchain == 'LLVM'
         run: |
            set -e
 
@@ -283,6 +410,8 @@ jobs:
            echo "CROSS_COMPILE=aarch64-linux-gnu-" >> $GITHUB_ENV
     
            echo "✅ GKI Toolchain setup complete."
+
+      # ====================== Configurations Tool Stage ======================
           
       - name: "📐 Setup SWAP 24GB"
         uses: pierotofy/set-swap-space@master
