Update test_z.yml

diff --git a/.github/workflows/test_z.yml b/.github/workflows/test_z.yml
--- a/.github/workflows/test_z.yml
+++ b/.github/workflows/test_z.yml
@@ -218,6 +218,41 @@ jobs:
            -e '/^MODULES_LIST=/d' \
            ${{ env.kernelDir }}/${{ env.kernelName }}/build.config.gki.aarch64
 
+      - name: "🛠 Setup kernel Tweaks"
+        working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
+        run: |
+          set -e
+
+          log() {
+            echo "$(date '+%Y-%m-%d %H:%M:%S') - $1"
+          }
+
+          apply_patch() {
+            local patch="$1"
+            local error_msg="$2"
+
+            log "Attempting to apply patch: $(basename "$patch")"
+
+            if ! patch -p1 < "$patch"; then
+              log "Warning: Some hunks failed while applying patch $(basename "$patch")"
+            fi
+          }
+          PATCH_URL="https://raw.githubusercontent.com/nebixts/kernel_patches/main/0001-fs-lineageos-disguise.patch"
+          PATCH_FILE="0001-fs-lineageos-disguise.patch"
+
+          log "Downloading patch from $PATCH_URL"
+
+          curl -L -o "$PATCH_FILE" "$PATCH_URL"
+
+          if [ ! -f "$PATCH_FILE" ]; then
+            log "Patch file $PATCH_FILE does not exist after download"
+            exit 1
+          fi
+
+          apply_patch "$PATCH_FILE"
+
+          log "✅ Patch applied successfully"
+      
       - name: "⚙️ Configure kernel optimization and tick rate"
         working-directory: ./${{ env.kernelDir }}/${{ env.kernelName }}
         run: |
@@ -830,7 +865,7 @@ jobs:
           if [ "${{ github.event.inputs.buildKSU }}" != "noksu" ]; then
             KSU_INFO="_${{ github.event.inputs.ksuVariant }}"
           fi
-          ZIP_NAME="Anykernel3_${{ github.event.inputs.kernelBranch }}${KSU_INFO}_${{ github.event.inputs.optimizationLevel }}_${{ github.event.inputs.tickRate }}hz_${BUILD_TIME}.zip"
+          ZIP_NAME="NeFaRiaN_${{ github.event.inputs.kernelBranch }}${KSU_INFO}_${{ github.event.inputs.optimizationLevel }}_${{ github.event.inputs.tickRate }}hz_${BUILD_TIME}.zip"
           cd AnyKernel3
           zip -r9 "../$ZIP_NAME" * -x .git/*
           cd ..
